/*
MIT License

Copyright (c) 2026 jmfrohs

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

const translations = {
  en: {
    settings: 'Settings',
    voice_commands: 'Voice Commands',
    reporting: 'Reporting',
    dark_mode: 'Dark Mode',
    target_type: 'Target Type',
    language: 'Language',
    auto_submit: 'Auto-Submit Report',
    theme_color: 'Theme Color',
    device_size: 'Device Size',
    click_value: 'Click Value',
    range_distance: 'Range Distance',
    auto_save: 'Auto-Save Sessions',
    auto_save_desc: 'Save automatically after 5 shots',
    clear_data: 'Clear All Data',
    athletes: 'Athletes',
    sessions: 'Sessions',
    analytics: 'Analytics',
    trainings: 'Trainings',
    view_athlete_stats: 'Performance by athlete',
    view_session_stats: 'Performance by session',
    view_athlete_stats_short: 'By athlete',
    view_session_stats_short: 'By session',
    select_view: 'Select View',
    overall_stats: 'Overall Statistics',
    no_series_found: 'No series found',
    select_click_value: 'Select Click Value',
    click_value_desc: 'Impact shift per click at 50m.',
    mm_per_click: 'mm/click',
    mm: 'mm',
    mm_short: 'mm',
    click_value: 'Click Value',
    shots_hits: 'Shots & Hits',
    stance: 'Stance',
    adjustments: 'Adjustments',
    system: 'System',
    close: 'Close',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    back: 'Back',
    settings_subtitle: 'Configure your assistant',
    appearance: 'Appearance',
    target_and_range: 'Target & Range',
    general: 'General',
    recipients: 'Recipients',
    test_send: 'Test Send',
    manage_custom_targets: 'Manage Custom Targets',
    shooting_time_defaults: 'Shooting Time Defaults',
    prone_adjustment: 'Prone Adjustment',
    standing_adjustment: 'Standing Adjustment',
    seconds_added: 'Added to shooting time',
    sec: 'sec',
    confirm_delete_title: 'Clear All Data?',
    confirm_delete_msg:
      'This will permanently delete all athletes, sessions, and settings. This action cannot be undone.',
    type_delete: 'Type DELETE to confirm:',
    type_delete_pre: 'Type ',
    type_delete_post: ' to confirm:',
    delete_all: 'Delete All',
    select_target_type: 'Select Target Type',
    choose_target_type_desc: 'Choose the target type for your shooting practice.',
    search_athletes_placeholder: 'Search athletes...',
    active_rosters: 'Active Rosters',
    no_athletes: 'No athletes found.',
    no_group: 'No Group',
    confirm_delete_athlete: 'Are you sure you want to delete this athlete?',
    enter_athlete_name: 'New Athlete Name:',
    no_shots_recorded: 'No shots recorded',
    athlete_not_found: 'Athlete not found',
    error_saving: 'Error saving:',
    shots_saved_msg: 'shots saved for',
    coach_account: 'Coach Account',
    search_placeholder: 'Search sessions...',
    filter_all: 'All',
    competitions: 'Competitions',
    training: 'Training',
    no_recent_sessions: 'No more recent sessions',
    confirm_delete_session: 'Are you sure you want to delete this session?',
    no_sessions: 'No sessions found',
    today: 'Today',
    yesterday: 'Yesterday',
    delete: 'Delete',
    cancel: 'Cancel',
    performance_insights: 'Performance Insights & Stats',
    analysis_insights: 'Analysis & Insights',
    shot_distribution: 'Shot Distribution',
    heatmap: 'Heatmap',
    combined_accuracy: 'Combined Accuracy',
    all_shots: 'All Shots',
    performance_trend: 'Performance Trend',
    hit_rate_over_time: 'Hit Rate %',
    heatmap_analysis: 'Heatmap Analysis',
    no_trend_data: 'No data for trend',
    analytics_description:
      'Comprehensive overview of shooting performance, combining heatmaps for density analysis and target overlays for exact grouping visualization.',
    target_analysis: 'Target Analysis',
    edit_series: 'Edit Series',
    no_athletes_filter: 'No athletes found for this filter.',
    history: 'History',
    series: 'Series',
    no_series_filter: 'No series found for this filter.',
    zeroing: 'Zeroing',
    unknown_location: 'Unknown',
    large_view: 'Large View',
    avg_ring: 'Ø Ring',
    total_time: 'Total Time',
    shot_details: 'Shot Details',
    start: 'Start',
    hit_rate: 'Hit Rate',
    avg_rings: 'Ø Rings',
    shots_count: 'Shots',
    new_session: 'New Session',
    create_manage: 'Create & Manage',
    session_name: 'Session Name',
    location: 'Location',
    session_date: 'Session Date',
    session_time: 'Session Time',
    session_type_placeholder: 'Session Type',
    testing: 'Testing',
    event_category: 'Event Category',
    race_type: 'Race Type',
    selected_label: 'selected',
    add_athletes_placeholder: 'Add athletes to this session...',
    create_session: 'Create Session',
    select_athletes: 'Select Athletes',
    search_name: 'Search name...',
    confirm_selection: 'Confirm Selection',
    no_athletes_found: 'No athletes found.',
    no_athletes_selected: 'No athletes selected',
    fill_all_details: 'Please fill in all session details',
    select_category_type: 'Please select event category and race type',
    select_one_athlete: 'Please select at least one athlete',
    sprint: 'Sprint',
    pursuit: 'Pursuit',
    individual: 'Individual',
    mass_start: 'Mass Start',
    relay: 'Relay',
    single_mixed_relay: 'Single Mixed Relay',
    mixed_relay: 'Mixed Relay',
    session_detail: 'Session Detail',
    loading: 'Loading...',
    session_settings: 'Session Settings',
    reporting: 'Reporting',
    email_report: 'Email Report',
    send_summary: 'Send summary after session',
    participation: 'Participation',
    add_remove: 'Add/Remove',
    delete_session: 'Delete Session',
    update_list_btn: 'Update List',
    no_name_neutral: 'Unnamed (Neutral)',
    no_assignment: 'No Assignment',
    new_series: 'New Series',
    no_series_recorded: 'No series recorded yet',
    start_left: 'Start: Left',
    start_right: 'Start: Right',
    delete_session_confirm: 'Delete this session?',
    next_series: 'Next Series',
    ready_for_shots: 'Ready for shots',
    select_recipients: 'Select Recipients',
    no_recipients_in_settings: 'No recipients configured in settings',
    weather_conditions: 'Weather Conditions',
    temperature: 'Temperature (°C)',
    wind_strength: 'Wind Strength',
    wind_direction: 'Wind Direction',
    sky_conditions: 'Sky Conditions',
    sunny: 'Sunny',
    cloudy: 'Cloudy',
    overcast: 'Overcast',
    rainy: 'Rainy',
    snowing: 'Snowing',
    foggy: 'Foggy',
    light: 'Light',
    moderate: 'Moderate',
    strong: 'Strong',
    stormy: 'Stormy',
    confirm_delete_series: 'Are you sure you want to delete this series?',
    series_saved: 'Series saved successfully!',
    left_short: 'Left',
    right_short: 'Right',
    up_short: 'Up',
    down_short: 'Down',
    clicks: 'Clicks',
    shot_label: 'Shot',
    time_label: 'Time',
    save: 'Save',
    cancel: 'Cancel',
    reset: 'Reset',
    wind_save: 'Save',
    group_shots_tooltip: 'Group shots (view only)',
    analysis_mode: 'Analysis Mode activated',
    normal_mode: 'Normal Mode',
    shots_grouped: 'Shots grouped',
    normal_view: 'Normal View',
    wind_adjusted: 'Wind adjusted',
    no_shots_save: 'No shots to save.',
    session_not_found: 'Error: Session not found.',
    shot_moved: 'Shot {n}: Moved to Ring {r} ({d})',
    correction: 'Correction: ',
    none: 'None',
    dir_right_bottom: 'bottom right',
    dir_bottom: 'bottom',
    dir_left_bottom: 'bottom left',
    dir_left: 'left',
    dir_left_top: 'top left',
    dir_top: 'top',
    dir_right_top: 'top right',
    dir_right: 'right',
    dir_center: 'center',
    series_finished: 'Series finished.',
    session_settings: 'Session Settings',
    loading: 'Loading...',
    reporting: 'Reporting',
    email_report: 'Email Report',
    send_summary_after: 'Send summary after session',
    detailed_stats: 'Detailed Stats',
    include_shot_analysis: 'Include shot analysis',
    modify_list: 'Modify List',
    manage_athletes: 'Manage Athletes',
    update_participation: 'Update Participation',
    delete_session: 'Delete Session',
    no_athletes_selected: 'No athletes selected.',
    no_group: 'No Group',
    delete_session_confirm: 'Are you sure you want to delete this session? This cannot be undone.',
    add_athlete: 'Add Athlete',
    edit_athlete: 'Edit Athlete',
    new_athlete: 'New Athlete',
    first_name: 'First Name',
    last_name: 'Last Name',
    date_of_birth: 'Date of Birth',
    age: 'Age',
    age_group: 'Age Group',
    squad_kader: 'Squad/Kader',
    nothing: 'Nothing',
    shooting_preference: 'Shooting Preference',
    prone_start: 'Prone Start',
    standing_start: 'Standing Start',
    left: 'Left',
    right: 'Right',
    shooting_time_adjustments: 'Shooting Time Adjustments',
    use_global_defaults: 'Use Global Defaults',
    prone_plus_sec: 'Prone (+ sec)',
    standing_plus_sec: 'Standing (+ sec)',
    save_athlete: 'Save Athlete',
    athlete_saved_success: '✓ Athlete saved successfully',
    update_athlete: 'Update Athlete',
    update_profile: 'Update Profile',
    please_enter_name_dob: 'Please enter first name, last name, and date of birth',
    please_select_age_squad: 'Please select age group and squad',
    athlete_updated_success: '✓ Athlete updated successfully!',
    analytics: 'Analytics',
    performance_insights: 'Performance Insights & Stats',
    analysis_insights: 'Analysis & Insights',
    hit_rate: 'Hit Rate',
    avg_rings: 'Ø Rings',
    shots_count: 'Shots',
    shot_distribution: 'Shot Distribution',
    heatmap: 'Heatmap',
    combined_accuracy: 'Combined Accuracy',
    all_shots: 'All Shots',
    analytics_description:
      'Comprehensive overview of shooting performance, combining heatmaps for density analysis and target overlays for exact grouping visualization.',
    target_analysis: 'Target Analysis',
    edit_series: 'Edit Series',
    filter_all: 'All',
    no_athletes_filter: 'No athletes found with current filter.',
    history: 'History',
    no_series_filter: 'No series found with current filter.',
    competitions: 'Competitions',
    trainer_name: 'Trainer Name',
    trainer_name_placeholder: 'Enter trainer name...',
    api_configuration: 'API Configuration',
    setup_guide: 'Setup Guide',
    emailjs_public_key: 'EmailJS Public Key',
    emailjs_service_id: 'EmailJS Service ID',
    emailjs_template_id: 'EmailJS Template ID',
    public_key_placeholder: 'Your Public Key',
    service_id_placeholder: 'service_xxxxxxx',
    template_id_placeholder: 'template_xxxxxxx',
    save_config: 'Save Configuration',
    add_trainer_email: 'Add trainer email...',
    email_not_configured: 'Email not configured. Please set up EmailJS credentials.',
    emailjs_not_loaded: 'EmailJS library not loaded.',
    unknown_athlete: 'Unknown Athlete',
    ring: 'Ring',
    hit: 'Hit',
    miss: 'Miss',
    email_sent_success: 'Email sent successfully!',
    email_send_error: 'Error sending email',
    test_email_sent: 'Test email sent successfully!',
    config_saved: 'Configuration saved successfully!',
    delete: 'Delete',
    invalid_email: 'Invalid email address',
    email_exists: 'Email already exists',
    no_recipients: 'No recipients added',
    recipient_added: 'Recipient added successfully',
    click_value: 'Click Value',
    custom_value: 'Custom Value',
    apply: 'Apply',
    click_value_range: 'Range: 0.5 - 10.0 mm',
    invalid_click_value: 'Please enter a value between 0.5 and 10.0 mm',
    click_value_saved: 'Click value saved successfully',
    voice_recording: 'Recording...',
    voice_stopped: 'Voice stopped',
    voice_not_supported: 'Voice input not supported',
    voice_commands: 'Voice Commands',
    voice_commands_desc:
      'Activate voice input by clicking the microphone button during shooting. Speak commands in German or English.',
    show_all_commands: 'Show All Commands',
    vc_shot_entry: 'Shot Entry',
    vc_basic: 'Basic',
    vc_miss: 'Miss',
    vc_undo: 'Undo',
    vc_stance: 'Stance',
    vc_prone: 'Prone',
    vc_standing: 'Standing',
    vc_sight: 'Sight Adjustment',
    vc_directions: 'Directions',
    vc_multiple: 'Multiple Clicks',
    vc_reset: 'Reset',
    vc_toggle: 'Modes & Features',
    vc_ghost: 'Ghost Markers',
    vc_grouping: 'Grouping',
    vc_wind: 'Wind',
    vc_open_wind: 'Open Wind Modal',
    vc_set_wind: 'Set Value',
    vc_navigation: 'Navigation',
    vc_save: 'Save Series',
    vc_next_athlete: 'Next Athlete',
    vc_prev_athlete: 'Previous Athlete',
    vc_back: 'Back to Overview',
    vc_tip:
      '💡 Tip: Speak clearly and wait for the status message to confirm the command was recognized.',
    bias_angle: 'Direction Bias',
    bias_angle_desc: 'How strongly the spoken direction influences shot placement.',
    bias_off: 'Off',
    bias_low: 'Weak',
    bias_medium: 'Medium',
    bias_high: 'Strong',
    shot_size: 'Shot Size',
    select_shot_size: 'Select Shot Size',
    shot_size_desc: 'Choose the visual size of the shot markers on the target.',
    shot_size_small: 'Small (4px)',
    shot_size_medium: 'Medium (6px)',
    shot_size_large: 'Large (8px)',
    shot_size_xl: 'Extra Large (10px)',
    shot_size_range: 'Range: 2 - 20 px',
    shot_size_invalid: 'Please enter a value between 2 and 20 px',
    shot_appearance: 'Shot Appearance',
    shot_options: 'Shot Options',
    hit_color: 'Hit Color',
    miss_color: 'Miss Color',
    shot_label_color: 'Shot Label Color',
    hit_label_color: 'Hit Label Color',
    miss_label_color: 'Miss Label Color',
    ghost_shot_color: 'Ghost Marker Color',
    ghost_label_color: 'Ghost Label Color',
    shot_label_content: 'Label Content',
    label_number: 'Number (1-5)',
    label_ring: 'Ring Value',
    label_none: 'None',
    reset_to_default: 'Reset to Default',
    import_data: 'Import Data',
    import_performance: 'Import Performance',
    import_instructions_main: 'Drag and drop a PDF or Excel file containing shooting results.',
    import_instructions_sub: 'The app will try to match athletes and extract hit patterns.',
    drop_file_here: 'Drop file here',
    or_click_to_browse: 'or click to browse',
    extracted_data: 'Extracted Data',
    confirm_import: 'Create Session & Import',
    no_file_selected: 'No file processed yet',
    processing_file: 'Processing file...',
    data_management: 'Data & Support',
    export_session: 'Export Session',
    export_pdf: 'Export PDF',
    export_excel: 'Export Excel',
    age_group_short: 'Class',
    name: 'Name',
    total: 'Total',
    intensity_ring_visible: 'Show Intensity Ring',
    intensity_ring_visible_desc: 'Display a colored ring around shots based on intensity level',
    sharing: 'Sharing',
    share_session: 'Share Session',
    sharing_active: 'Sharing Active',
    sharing_inactive: 'Invite a partner',
    confirm_stop_sharing: 'Are you sure you want to stop sharing this session?',
    auto_save_delay: 'Auto-Save Delay',
    account_settings: 'Account Settings',
    user_role: 'User Role',
    role_coach: 'Coach',
    role_coach_desc: 'Manages multiple athletes',
    role_athlete: 'Athlete',
    role_athlete_desc: 'Personal shooting data',
    select_role: 'Select Role',
    athlete_account: 'Athlete Account',
    profile: 'Profile',
    personal_data: 'Personal',
  },
  de: {
    settings: 'Einstellungen',
    voice_commands: 'Sprachbefehle',
    reporting: 'Berichte',
    dark_mode: 'Dunkelmodus',
    target_type: 'Scheibentyp',
    language: 'Sprache',
    auto_submit: 'Automatisch Senden',
    theme_color: 'Themenfarbe',
    device_size: 'Gerätegröße',
    click_value: 'Klick-Korrektur',
    range_distance: 'Entfernung',
    auto_save: 'Auto-Speichern',
    auto_save_desc: 'Nach 5 Schüssen automatisch speichern',
    clear_data: 'Alle Daten löschen',
    athletes: 'Athleten',
    sessions: 'Sitzungen',
    analytics: 'Analyse',
    trainings: 'Trainings',
    view_athlete_stats: 'Statistiken nach Sportler',
    view_session_stats: 'Statistiken nach Training',
    view_athlete_stats_short: 'Nach Sportler',
    view_session_stats_short: 'Nach Training',
    select_view: 'Ansicht wählen',
    overall_stats: 'Gesamtstatistik',
    no_series_found: 'Keine Serien gefunden',
    select_click_value: 'Klick-Wert wählen',
    click_value_desc: 'Treffpunktverlagerung pro Klick auf 50m.',
    mm_per_click: 'mm/Klick',
    mm: 'mm',
    mm_short: 'mm',
    shots_hits: 'Schüsse & Treffer',
    stance: 'Anschlag',
    adjustments: 'Korrekturen',
    system: 'System',
    close: 'Schließen',
    save: 'Speichern',
    cancel: 'Abbrechen',
    delete: 'Löschen',
    edit: 'Bearbeiten',
    back: 'Zurück',
    settings_subtitle: 'Konfiguriere deinen Assistenten',
    appearance: 'Aussehen',
    target_and_range: 'Scheibe & Stand',
    general: 'Allgemein',
    recipients: 'Empfänger',
    test_send: 'Test Senden',
    manage_custom_targets: 'Eigene Scheiben verwalten',
    shooting_time_defaults: 'Standard Schießzeiten',
    prone_adjustment: 'Zeitkorrektur Liegend',
    standing_adjustment: 'Zeitkorrektur Stehend',
    seconds_added: 'Zur Schießzeit addiert',
    sec: 'sek',
    confirm_delete_title: 'Alle Daten löschen?',
    confirm_delete_msg: 'Dies löscht unwiderruflich alle Athleten, Sitzungen und Einstellungen.',
    type_delete: 'Tippe DELETE zum Bestätigen:',
    type_delete_pre: 'Tippe ',
    type_delete_post: ' zum Bestätigen:',
    delete_all: 'Alles löschen',
    select_target_type: 'Scheibentyp wählen',
    choose_target_type_desc: 'Wähle den Scheibentyp für dein Training.',
    search_athletes_placeholder: 'Athleten suchen...',
    active_rosters: 'Aktive Kader',
    no_athletes: 'Keine Athleten gefunden.',
    no_group: 'Keine Gruppe',
    confirm_delete_athlete: 'Möchtest du diesen Athleten wirklich löschen?',
    enter_athlete_name: 'Name des neuen Athleten:',
    no_shots_recorded: 'Keine Schüsse aufgezeichnet',
    athlete_not_found: 'Athlet nicht gefunden',
    error_saving: 'Fehler beim Speichern:',
    shots_saved_msg: 'Schüsse gespeichert für',
    coach_account: 'Trainer Account',
    search_placeholder: 'Sitzungen suchen...',
    filter_all: 'Alle',
    competitions: 'Wettkampf',
    training: 'Training',
    no_recent_sessions: 'Keine weiteren Sitzungen',
    confirm_delete_session: 'Möchtest du diese Sitzung wirklich löschen?',
    no_sessions: 'Keine Sitzungen gefunden',
    today: 'Heute',
    yesterday: 'Gestern',
    performance_insights: 'Leistungsübersicht & Statistiken',
    analysis_insights: 'Analyse & Erkenntnisse',
    shot_distribution: 'Schussverteilung',
    heatmap: 'Heatmap',
    combined_accuracy: 'Kombinierte Genauigkeit',
    all_shots: 'Alle Schüsse',
    performance_trend: 'Leistungsverlauf',
    hit_rate_over_time: 'Trefferquote %',
    heatmap_analysis: 'Heatmap Analyse',
    no_trend_data: 'Keine Daten für Trend',
    analytics_description:
      'Umfassender Überblick über die Schießleistung, Kombination von Heatmaps für Dichteanalyse und Trefferbildern für exakte Gruppierungsvisualisierung.',
    target_analysis: 'Treffbild Analyse',
    edit_series: 'Serie bearbeiten',
    no_athletes_filter: 'Keine Athleten für diesen Filter gefunden.',
    history: 'Verlauf',
    series: 'Serien',
    no_series_filter: 'Keine Serien für diesen Filter gefunden.',
    zeroing: 'Anschießen',
    unknown_location: 'Unbekannt',
    large_view: 'Großansicht',
    avg_ring: 'Ø Ring',
    total_time: 'Gesamtzeit',
    shot_details: 'Schuss-Details',
    start: 'Start',
    hit_rate: 'Trefferquote',
    avg_rings: 'Ø Ringe',
    shots_count: 'Schüsse',
    new_session: 'Neue Sitzung',
    create_manage: 'Erstellen & Verwalten',
    session_name: 'Sitzungsname',
    location: 'Ort',
    session_date: 'Datum',
    session_time: 'Uhrzeit',
    session_type_placeholder: 'Sitzungstyp',
    testing: 'Test',
    event_category: 'Wettkampf Kategorie',
    race_type: 'Renntyp',
    selected_label: 'ausgewählt',
    add_athletes_placeholder: 'Athleten hinzufügen...',
    create_session: 'Sitzung erstellen',
    select_athletes: 'Athleten auswählen',
    search_name: 'Name suchen...',
    confirm_selection: 'Auswahl bestätigen',
    no_athletes_found: 'Keine Athleten gefunden.',
    no_athletes_selected: 'Keine Athleten ausgewählt',
    fill_all_details: 'Bitte alle Details ausfüllen',
    select_category_type: 'Bitte Kategorie und Renntyp wählen',
    select_one_athlete: 'Bitte mindestens einen Athleten wählen',
    sprint: 'Sprint',
    pursuit: 'Verfolgung',
    individual: 'Einzel',
    mass_start: 'Massenstart',
    relay: 'Staffel',
    single_mixed_relay: 'Single Mixed Staffel',
    mixed_relay: 'Mixed Staffel',
    session_detail: 'Sitzungsdetails',
    loading: 'Laden...',
    session_settings: 'Sitzungseinstellungen',
    reporting: 'Bericht',
    email_report: 'Email Bericht',
    send_summary: 'Zusammenfassung nach Sitzung senden',
    participation: 'Teilnehmer',
    add_remove: 'Hinzufügen/Entfernen',
    delete_session: 'Sitzung löschen',
    update_list_btn: 'Liste aktualisieren',
    no_name_neutral: 'Ohne Namen (Neutral)',
    no_assignment: 'Keine Zuordnung',
    new_series: 'Neue Serie',
    no_series_recorded: 'Noch keine Serien aufgenommen',
    start_left: 'Start: Links',
    start_right: 'Start: Rechts',
    delete_session_confirm: 'Diese Sitzung löschen?',
    next_series: 'Nächste Serie',
    ready_for_shots: 'Bereit für Schüsse',
    select_recipients: 'Empfänger auswählen',
    no_recipients_in_settings: 'Keine Empfänger in den Einstellungen konfiguriert',
    series_saved: 'Serie erfolgreich gespeichert!',
    left_short: 'Links',
    right_short: 'Rechts',
    up_short: 'Hoch',
    down_short: 'Tief',
    clicks: 'Klicks',
    shot_label: 'Schuss',
    time_label: 'Zeit',
    save: 'Speichern',
    cancel: 'Abbr.',
    reset: 'Reset',
    wind_save: 'Speichern',
    group_shots_tooltip: 'Schüsse gruppieren (nur Ansicht)',
    analysis_mode: 'Analyse-Modus aktiviert',
    normal_mode: 'Normal-Modus',
    shots_grouped: 'Schüsse gruppiert',
    normal_view: 'Normal-Ansicht',
    wind_adjusted: 'Wind angepasst',
    no_shots_save: 'Keine Schüsse zum Speichern vorhanden.',
    session_not_found: 'Fehler: Sitzung nicht gefunden.',
    shot_moved: 'Schuss {n}: Bewegt nach Ring {r} ({d})',
    correction: 'Korrektur: ',
    none: 'Kein',
    dir_right_bottom: 'rechts unten',
    dir_bottom: 'unten',
    dir_left_bottom: 'links unten',
    dir_left: 'links',
    dir_left_top: 'links hoch',
    dir_top: 'oben',
    dir_right_top: 'rechts hoch',
    dir_right: 'rechts',
    dir_center: 'zentrum',
    series_finished: 'Serie abgeschlossen.',
    session_settings: 'Sitzungseinstellungen',
    loading: 'Laden...',
    reporting: 'Berichte',
    email_report: 'E-Mail-Bericht',
    send_summary_after: 'Zusammenfassung nach Sitzung senden',
    detailed_stats: 'Detaillierte Statistiken',
    include_shot_analysis: 'Schussanalyse einbeziehen',
    modify_list: 'Liste ändern',
    manage_athletes: 'Athleten verwalten',
    update_participation: 'Teilnahme aktualisieren',
    delete_session: 'Sitzung löschen',
    no_athletes_selected: 'Keine Athleten ausgewählt.',
    no_group: 'Keine Gruppe',
    delete_session_confirm:
      'Sind Sie sicher, dass Sie diese Sitzung löschen möchten? Dies kann nicht rückgängig gemacht werden.',
    add_athlete: 'Athlet hinzufügen',
    edit_athlete: 'Athlet bearbeiten',
    new_athlete: 'Neuer Athlet',
    first_name: 'Vorname',
    last_name: 'Nachname',
    date_of_birth: 'Geburtsdatum',
    age: 'Alter',
    age_group: 'Altersgruppe',
    squad_kader: 'Kader',
    nothing: 'Nichts',
    shooting_preference: 'Schießpräferenz',
    prone_start: 'Liegend Start',
    standing_start: 'Stehend Start',
    left: 'Links',
    right: 'Rechts',
    shooting_time_adjustments: 'Schießzeit Anpassungen',
    use_global_defaults: 'Globale Standardwerte verwenden',
    prone_plus_sec: 'Liegend (+ Sek.)',
    standing_plus_sec: 'Stehend (+ Sek.)',
    save_athlete: 'Athlet speichern',
    athlete_saved_success: '✓ Athlet erfolgreich gespeichert',
    update_athlete: 'Athlet aktualisieren',
    update_profile: 'Profil aktualisieren',
    please_enter_name_dob: 'Bitte geben Sie Vorname, Nachname und Geburtsdatum ein',
    please_select_age_squad: 'Bitte wählen Sie Altersgruppe und Kader aus',
    weather_conditions: 'Wetterbedingungen',
    temperature: 'Temperatur (°C)',
    wind_strength: 'Windstärke',
    wind_direction: 'Windrichtung',
    sky_conditions: 'Himmel/Sicht',
    sunny: 'Sonnig',
    cloudy: 'Bewölkt',
    overcast: 'Bedeckt',
    rainy: 'Regen',
    snowing: 'Schnee',
    foggy: 'Nebel',
    light: 'Leicht',
    moderate: 'Mittel',
    strong: 'Stark',
    stormy: 'Stürmisch',
    confirm_delete_series: 'Möchtest du diese Serie wirklich löschen?',
    athlete_updated_success: '✓ Athlet erfolgreich aktualisiert!',
    analytics: 'Analytik',
    performance_insights: 'Leistungsübersicht & Statistiken',
    analysis_insights: 'Analyse & Einblicke',
    hit_rate: 'Trefferquote',
    avg_rings: 'Ø Ringe',
    shots_count: 'Schüsse',
    shot_distribution: 'Schussverteilung',
    heatmap: 'Heatmap',
    combined_accuracy: 'Kombinierte Genauigkeit',
    all_shots: 'Alle Schüsse',
    analytics_description:
      'Umfassende Übersicht der Schießleistung mit Heatmaps zur Dichteanalyse und Ziel-Overlays zur exakten Gruppierungsvisualisierung.',
    target_analysis: 'Treffbild Analyse',
    edit_series: 'Serie bearbeiten',
    filter_all: 'Alle',
    no_athletes_filter: 'Keine Athleten mit aktuellem Filter gefunden.',
    history: 'Verlauf',
    no_series_filter: 'Keine Serien mit aktuellem Filter gefunden.',
    competitions: 'Wettkämpfe',
    trainer_name: 'Trainername',
    trainer_name_placeholder: 'Trainername eingeben...',
    api_configuration: 'API-Konfiguration',
    setup_guide: 'Einrichtungsanleitung',
    emailjs_public_key: 'EmailJS Public Key',
    emailjs_service_id: 'EmailJS Service ID',
    emailjs_template_id: 'EmailJS Template ID',
    public_key_placeholder: 'Dein Public Key',
    service_id_placeholder: 'service_xxxxxxx',
    template_id_placeholder: 'template_xxxxxxx',
    save_config: 'Konfiguration Speichern',
    add_trainer_email: 'Trainer-E-Mail hinzufügen...',
    email_not_configured: 'E-Mail nicht konfiguriert. Bitte EmailJS-Zugangsdaten einrichten.',
    emailjs_not_loaded: 'EmailJS-Bibliothek nicht geladen.',
    unknown_athlete: 'Unbekannter Athlet',
    ring: 'Ring',
    hit: 'Treffer',
    miss: 'Fehler',
    email_sent_success: 'E-Mail erfolgreich gesendet!',
    email_send_error: 'Fehler beim E-Mail-Versand',
    test_email_sent: 'Test-E-Mail erfolgreich gesendet!',
    config_saved: 'Konfiguration erfolgreich gespeichert!',
    delete: 'Löschen',
    invalid_email: 'Ungültige E-Mail-Adresse',
    email_exists: 'E-Mail bereits vorhanden',
    no_recipients: 'Keine Empfänger hinzugefügt',
    recipient_added: 'Empfänger erfolgreich hinzugefügt',
    click_value: 'Klick-Wert',
    custom_value: 'Eigener Wert',
    apply: 'Anwenden',
    click_value_range: 'Bereich: 0,5 - 10,0 mm',
    invalid_click_value: 'Bitte geben Sie einen Wert zwischen 0,5 und 10,0 mm ein',
    click_value_saved: 'Klick-Wert erfolgreich gespeichert',
    voice_recording: 'Aufnahme läuft...',
    voice_stopped: 'Spracheingabe gestoppt',
    voice_not_supported: 'Spracheingabe wird nicht unterstützt',
    voice_commands: 'Sprachbefehle',
    voice_commands_desc:
      'Aktivieren Sie die Spracheingabe durch Klick auf das Mikrofon-Symbol beim Schießen. Sprechen Sie Befehle auf Deutsch oder Englisch.',
    show_all_commands: 'Alle Befehle anzeigen',
    vc_shot_entry: 'Schuss-Eingabe',
    vc_basic: 'Grundbefehle',
    vc_miss: 'Fehlschuss',
    vc_undo: 'Rückgängig',
    vc_stance: 'Haltung',
    vc_prone: 'Liegend',
    vc_standing: 'Stehend',
    vc_sight: 'Visierverstellung',
    vc_directions: 'Richtungen',
    vc_multiple: 'Mehrere Klicks',
    vc_reset: 'Zurücksetzen',
    vc_toggle: 'Modi & Features',
    vc_ghost: 'Geister-Marker',
    vc_grouping: 'Gruppierung',
    vc_wind: 'Wind',
    vc_open_wind: 'Wind-Modal öffnen',
    vc_set_wind: 'Wert setzen',
    vc_navigation: 'Navigation',
    vc_save: 'Serie speichern',
    vc_next_athlete: 'Nächster Schütze',
    vc_prev_athlete: 'Vorheriger Schütze',
    vc_back: 'Zurück zur Übersicht',
    vc_tip: '💡 Tipp: Sprechen Sie klar und warten Sie auf die Statusmeldung zur Bestätigung.',
    bias_angle: 'Richtungs-Bias',
    bias_angle_desc:
      'Wie stark die genannte Richtung die Schussplatzierung bei der Spracheingabe beeinflusst.',
    bias_off: 'Aus',
    bias_low: 'Schwach',
    bias_medium: 'Mittel',
    bias_high: 'Stark',
    shot_size: 'Schussgröße',
    select_shot_size: 'Schussgröße auswählen',
    shot_size_desc: 'Wähle die visuelle Größe der Schussmarkierungen auf der Scheibe.',
    shot_size_small: 'Klein (4px)',
    shot_size_medium: 'Mittel (6px)',
    shot_size_large: 'Groß (8px)',
    shot_size_xl: 'Extra Groß (10px)',
    shot_size_range: 'Bereich: 2 - 20 px',
    shot_size_invalid: 'Bitte gib einen Wert zwischen 2 und 20 px ein',
    shot_appearance: 'Schuss-Aussehen',
    shot_options: 'Schuss-Optionen',
    hit_color: 'Treffer-Farbe',
    miss_color: 'Fehler-Farbe',
    shot_label_color: 'Schussnummer-Farbe',
    hit_label_color: 'Treffer-Schriftfarbe',
    miss_label_color: 'Fehler-Schriftfarbe',
    ghost_shot_color: 'Analyse-Marker Farbe',
    ghost_label_color: 'Analyse-Schriftfarbe',
    shot_label_content: 'Schussbeschriftung',
    label_number: 'Nummer (1-5)',
    label_ring: 'Ringwert',
    label_none: 'Keine',
    reset_to_default: 'Auf Standard zurücksetzen',
    import_data: 'Daten importieren',
    import_performance: 'Leistung importieren',
    import_instructions_main:
      'Ziehen Sie eine PDF- oder Excel-Datei mit Schießergebnissen hierher.',
    import_instructions_sub:
      'Die App versucht, Athleten zuzuordnen und Treffermuster zu extrahieren.',
    drop_file_here: 'Datei hier ablegen',
    or_click_to_browse: 'oder klicken zum Durchsuchen',
    extracted_data: 'Extrahierte Daten',
    confirm_import: 'Neue Session erstellen & importieren',
    no_file_selected: 'Noch keine Datei verarbeitet',
    processing_file: 'Datei wird verarbeitet...',
    data_management: 'Daten & Support',
    export_session: 'Session exportieren',
    export_pdf: 'PDF Export',
    export_excel: 'Excel Export',
    age_group_short: 'Klasse',
    name: 'Name',
    total: 'Gesamt',
    intensity_ring_visible: 'Intensitätsring anzeigen',
    intensity_ring_visible_desc: 'Farbiger Ring um Schüsse je nach Intensitätsstufe',
    sharing: 'Sharing',
    share_session: 'Session teilen',
    sharing_active: 'Teilen aktiv',
    sharing_inactive: 'Lade Partner ein',
    confirm_stop_sharing: 'Möchtest du das Teilen wirklich beenden?',
    gui_scale: 'GUI-Skalierung',
    auto_save_delay: 'Auto-Speicher Verzögerung',
    account_settings: 'Kontoeinstellungen',
    user_role: 'Benutzerrolle',
    role_coach: 'Coach',
    role_coach_desc: 'Verwaltet mehrere Athleten',
    role_athlete: 'Sportler',
    role_athlete_desc: 'Eigene Datenerfassung',
    select_role: 'Rolle wählen',
    athlete_account: 'Sportler Account',
    profile: 'Profil',
    personal_data: 'Persönlich',
  },
};

function t(key) {
  if (typeof getLanguage === 'undefined') {
    return key;
  }

  const lang = getLanguage() || 'de';
  if (translations[lang] && translations[lang][key]) {
    return translations[lang][key];
  }

  if (translations['en'] && translations['en'][key]) {
    return translations['en'][key];
  }
  return key;
}
